name: Continuous Integration

on:
  # Run for any commit in origin repository
  push:
  # And pull requests from forks
  pull_request:
    branches:
      # This avoids running the job twice for PRs from origin repository
    - '**:**'

jobs:
  build_and_test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: kinetic
    - uses: ros-tooling/action-ros-ci@v0.1
      with:
        package-name: ca_description ca_driver ca_msgs ca_tools create_autonomy
        target-ros1-distro: kinetic
        vcs-repo-file-url: ""
